// projects/mice-and-dragons/src/game/board.tsx
import React from 'react';
import Square from './square';
import './board.scss';

export default function Board(props: { squares: number[], inProgress: boolean, onClick: any }) {
    const handlePickSquare = (square: any, value: number) => {
        return 0;
    };

    return (
        <div>
            {(props.inProgress === true) &&
                <div className="board">
                    {props.squares.map((square, index) => {
                        return (<Square token={square} key={index} onClick={(e: number) => props.onClick(index, e)}></Square>);
                    })}
                </div>
            }
        </div>

    );
}

// projects/rock-n-roll/src/components/Board.vue
<template>
  <div class="board-container">
    <div class="board-square" v-for="(square, index) in squares" :key="index">
      <Square :value="square"></Square>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue, } from 'vue-property-decorator';
import Square from './Square.vue';

@Component({
  name: 'board',
  components: {
    Square,
  }
})
export default class Board extends Vue {
  @Prop() private squares!: [];
}
</script>

<style lang="scss">
.board-container {
  box-sizing: border-box;
  display: flex;
  flex-wrap: wrap;
  flex-direction: row;
  // flex-basis: 33%;
}

.board-square {

  flex: 1 0 30%;
}
</style>
