// projects/rock-n-roll/src/components/Square.vue
<template>
  <div class="square" v-on:click="() => selectSquare()">
    <span class="player-square">{{getSquareAvatar(value)}}</span>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue, } from 'vue-property-decorator';
import { getAvatar } from '../gameLogic';

@Component
export default class Square extends Vue {
  @Prop() value?: string;

  selectSquare() {
    this.$emit('select');
  }

  getSquareAvatar(player: number) {
    return getAvatar(player);
  }
}
</script>

<style lang="scss">
.square {
  display: flex;
  min-width: 100px;
  min-height: 100px;
  border: 1px solid blue;
  background-color: purple;
  justify-content: center;
  align-items: center;
}

.player-square {
  font-size: 4vw;
}
</style>

// projects/unicorns-and-dragons/src/game/square.svelte
<script>
  import { avatars } from "../GameState.js";
  export let player = 0;
</script>

<style>
  .square {
    width: 100%;
    height: 100%;
    background-color: red;
    text-align: center;
    justify-content: center;
    align-items: center;
    display: flex;
    border-radius: 10px;
  }

  .avatar {
    font-size: xx-large;
  }
</style>

<div
  class="square avatar"
  style={`background-color: ${$avatars[player].color}`}
  on:click>
  {$avatars[player].icon}
  <br />
</div>
